# fly.toml app configuration file generated for grow-agent-bolt on 2024-12-26T06:46:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grow-agent-bolt'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
